name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install composer and dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        env:
          COMPOSER_CACHE_DIR: /tmp/composer_cache

      - name: Run PHPMD
        run: ./vendor/bin/phpmd app,config,database,routes github phpmd.rulesets.xml --exclude 'tests/*, vendor/*'
        continue-on-error: true

      - name: Verify PHP-CS-Fixer compliance
        if: ${{ always() }}
        run: |
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --diff --allow-risky=yes
        continue-on-error: true

      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit --colors=never

      - name: Upload PHPUnit coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: storage/framework/cache/data/coverage.xml
