name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
        run: cp .env.testing .env

      - name: Install composer and dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_database
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: php artisan test

      - name: Run PHPMD
        run: ./vendor/bin/phpmd app,config,database,routes github phpmd.rulesets.xml
        continue-on-error: false

      - name: Verify PHP-CS-Fixer compliance
        if: ${{ always() }}
        run: |
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --diff --allow-risky=yes
        continue-on-error: false
