name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          coverage: xdebug # Enable coverage using xdebug

      - name: Install composer and dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        env:
          COMPOSER_CACHE_DIR: /tmp/composer_cache

      - name: Run PHPMD
        run: phpmd . github phpmd.rulesets.xml --exclude 'tests/*, vendor/*'

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --diff

      - name: Verify PHP-CS-Fixer compliance
        if: ${{ always() }}
        run: |
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --diff
        continue-on-error: false

      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit --colors=never
